import { FormEvent, useState } from 'react';
import { Link, Route, Routes, useNavigate, useParams } from 'react-router-dom';

type Player={name:string;uid:string;ign:string;phone:string};
const initialPlayers:Player[]=[1,2,3,4].map(()=>({name:'',uid:'',ign:'',phone:''}));

function Layout({children}:{children:React.ReactNode}){
  return <div className="app"><header><Link className="brand" to="/">FF<span>TOURNAMENT</span></Link><nav><Link to="/register">Register</Link><Link to="/status">Status</Link><Link to="/privacy">Privacy</Link></nav></header><main>{children}</main><footer>Independent community tournament. Not affiliated with, sponsored by, or endorsed by Garena or Free Fire.</footer></div>
}
function Landing(){return <section className="hero"><div className="eyebrow">COMMUNITY ESPORTS • 2026</div><h1>BUILD YOUR<br/><em>SQUAD.</em></h1><p>Register your four-player team, keep your Team ID safe, and check your registration status anytime.</p><div className="actions"><Link className="btn primary" to="/register">REGISTER TEAM</Link><Link className="btn" to="/status">CHECK STATUS</Link></div><div className="cards"><div><b>4</b><span>Players / team</span></div><div><b>₹—</b><span>Entry fee</span></div><div><b>2026</b><span>Tournament year</span></div></div></section>}
function Register(){const nav=useNavigate();const[team,setTeam]=useState('');const[captain,setCaptain]=useState('');const[phone,setPhone]=useState('');const[players,setPlayers]=useState(initialPlayers);const[error,setError]=useState('');const update=(i:number,k:keyof Player,v:string)=>setPlayers(p=>p.map((x,n)=>n===i?{...x,[k]:v}:x));const submit=(e:FormEvent)=>{e.preventDefault();setError('');if(!team||!captain||!/^[6-9]\d{9}$/.test(phone)){setError('Enter team, captain and a valid 10-digit Indian mobile number.');return}if(players.some(p=>!p.name||!p.uid||!p.ign)){setError('Complete all four player profiles.');return}if(new Set(players.map(p=>p.uid)).size!==4){setError('Each player must have a unique Free Fire UID.');return}const code='FF2026-'+Math.random().toString(36).slice(2,7).toUpperCase();nav('/success/'+code)};return <section className="panel"><div className="eyebrow">TEAM REGISTRATION</div><h2>Enter your squad details</h2><p className="muted">Exactly four players are required.</p><form onSubmit={submit}><div className="grid two"><label>Team name*<input value={team} onChange={e=>setTeam(e.target.value)} placeholder="Example Esports"/></label><label>Captain name*<input value={captain} onChange={e=>setCaptain(e.target.value)} placeholder="Full name"/></label><label>Captain phone*<input value={phone} onChange={e=>setPhone(e.target.value)} inputMode="numeric" maxLength={10} placeholder="10-digit mobile"/></label><label>Email<input type="email" placeholder="Optional"/></label><label>College / organisation<input placeholder="Optional"/></label><label>City<input placeholder="City"/></label></div><h3>Players</h3>{players.map((p,i)=><div className="player" key={i}><strong>PLAYER {i+1}</strong><div className="grid two"><input value={p.name} onChange={e=>update(i,'name',e.target.value)} placeholder="Full name*"/><input value={p.uid} onChange={e=>update(i,'uid',e.target.value)} placeholder="Free Fire UID*"/><input value={p.ign} onChange={e=>update(i,'ign',e.target.value)} placeholder="In-game name*"/><input value={p.phone} onChange={e=>update(i,'phone',e.target.value)} placeholder="Phone (optional)"/></div></div>)}<label className="consent"><input type="checkbox" required/> I agree to the tournament privacy terms and confirm these details are accurate.</label>{error&&<div className="error">{error}</div>}<button className="btn primary wide">SUBMIT REGISTRATION</button></form></section>}
function Success(){const{code}=useParams();return <section className="panel center"><div className="success">✓</div><div className="eyebrow">REGISTRATION RECEIVED</div><h2>Your Team ID</h2><div className="teamcode">{code}</div><p className="muted">Save this Team ID and use it with the captain phone number on the Status page.</p><div className="actions"><Link className="btn primary" to="/status">CHECK STATUS</Link><Link className="btn" to="/">BACK HOME</Link></div></section>}
function Status(){const[code,setCode]=useState('');const[phone,setPhone]=useState('');const[checked,setChecked]=useState(false);return <section className="panel narrow"><div className="eyebrow">STATUS LOOKUP</div><h2>Check your registration</h2><p className="muted">Only the minimum status information is shown.</p><form onSubmit={e=>{e.preventDefault();setChecked(true)}}><label>Team ID<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="FF2026-XXXXX"/></label><label>Captain phone<input value={phone} onChange={e=>setPhone(e.target.value)} inputMode="numeric" maxLength={10} placeholder="10-digit mobile"/></label><button className="btn primary wide">LOOK UP</button></form>{checked&&<div className="result"><span>Team</span><b>{code||'—'}</b><span>Status</span><b>Pending verification</b><span>Payment</span><b>Pending</b></div>}</section>}
function Privacy(){return <section className="panel narrow"><div className="eyebrow">PRIVACY</div><h2>Your registration data</h2><p>Registration details are used only for tournament administration, verification and status lookup. Sensitive team and player data is not publicly listed.</p><p>Configure secure server-side storage, retention and deletion policies before opening public registration.</p><Link className="btn" to="/">BACK HOME</Link></section>}
export default function App(){return <Layout><Routes><Route path="/" element={<Landing/>}/><Route path="/register" element={<Register/>}/><Route path="/success/:code" element={<Success/>}/><Route path="/status" element={<Status/>}/><Route path="/privacy" element={<Privacy/>}/><Route path="*" element={<Landing/>}/></Routes></Layout>}